spring.application.name=restful.aiagent

server.port=8094

logging.file.name=/var/log/mvc-enterprises/aiagent-service.log
logging.level.root=INFO
logging.level.com.yourapp.controller=INFO
logging.level.com.yourapp.service=DEBUG
logging.level.org.springframework.web=ERROR
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n

spring.jpa.database=mysql
spring.datasource.url=jdbc:mysql://localhost:3306/pharma-compliance-model
spring.datasource.username=root
spring.datasource.password=44Tr$$Peta
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.cloud.config.import-check.enabled=false

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/actuator

management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

management.metrics.distribution.percentiles-histogram.login.processing.time=true

# Max file size per upload
spring.servlet.multipart.max-file-size=50MB
# Max request size (total)
spring.servlet.multipart.max-request-size=50MB
